### ISSUE TITLE
Python 3.8 build missing

### ISSUE THREAD

**Issue by jrbourbeau** [conda-forge/pytype-feedstock#4]
As of version 2020.6.1 pytype supports Python 3.8. This seems to be indicated in the recipe `meta.yaml` by skipping `py>=39` builds: 

https://github.com/conda-forge/pytype-feedstock/blob/b9bc7ff4d3277fa11f5d615cfb27d03983fe4564/recipe/meta.yaml#L15

However, I'm not able to conda install pytype into a Python 3.8 conda environment looking at the latest PR to the feedstock. For example:

```
$ conda create --name test -c conda-forge python=3.8 pytype
```

results in a `UnsatisfiableError` (full output below)

<details>
<summary>Output:</summary>

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
pytype -> attrs -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0|3.4.*|3.7.*']
pytype -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
python=3.8
```

</details>

Looking at the most recent PR (xref https://github.com/conda-forge/pytype-feedstock/pull/3) there doesn't appear to be a Python 3.8 build. Would it be possible to add a Python 3.8 build?

**Comment by marcelotrevisani** [comment]
Fixed with https://github.com/conda-forge/pytype-feedstock/pull/7
